import 'package:flutter/widgets.dart';

class AppLocalizations {
  const AppLocalizations(this.locale);

  final Locale locale;

  static const delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  String t(String text, [Map<String, Object?> args = const {}]) {
    final translations = switch (locale.languageCode) {
      'ar' => _arabic,
      _ => const <String, String>{},
    };
    var value = translations[text] ?? text;
    for (final entry in args.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value.toString());
    }
    return value;
  }
}

extension AppLocalizationX on BuildContext {
  String t(String text, [Map<String, Object?> args = const {}]) {
    return AppLocalizations.of(this).t(text, args);
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return const ['en', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

const _arabic = <String, String>{
  'Songs': 'الترانيم',
  'Favorites': 'المفضلة',
  'Notes': 'الملاحظات',
  'Playlists': 'قوائم التشغيل',
  'Piano Tutorials': 'دروس البيانو',
  'Scales': 'المقامات',
  'More': 'المزيد',
  'Circle': 'الدائرة',
  'Circle of Fifths': 'دائرة الخامسات',
  'Manage': 'إدارة',
  'Settings': 'الإعدادات',
  'Close navigation': 'إغلاق القائمة',
  'Open navigation': 'فتح القائمة',
  'Search': 'بحث',
  'Filter': 'تصفية',
  'Sort': 'ترتيب',
  'Sort chords': 'ترتيب الأوتار',
  'Sort scales': 'ترتيب المقامات',
  'Key order': 'ترتيب المفاتيح',
  'Manual order': 'ترتيب يدوي',
  'Add song': 'إضافة ترنيمة',
  'Edit Song': 'تعديل ترنيمة',
  'Add Song': 'إضافة ترنيمة',
  'Save': 'حفظ',
  'Cancel': 'إلغاء',
  'Apply': 'تطبيق',
  'Clear': 'مسح',
  'Add': 'إضافة',
  'Edit': 'تعديل',
  'Delete': 'حذف',
  'Remove': 'إزالة',
  'Rename': 'إعادة تسمية',
  'New': 'جديد',
  'All': 'الكل',
  'Any': 'أي',
  'Yes': 'نعم',
  'No': 'لا',
  'None': 'بدون',
  'Retry': 'إعادة المحاولة',
  'Back': 'رجوع',
  'Theme': 'المظهر',
  'System': 'النظام',
  'Light': 'فاتح',
  'Night': 'ليلي',
  'Language': 'اللغة',
  'English': 'الإنجليزية',
  'Arabic': 'العربية',
  'Major': 'كبير',
  'Minor': 'صغير',
  'Diminished': 'ناقص',
  'Major 7': 'كبير 7',
  'Minor 7': 'صغير 7',
  'Diminished 7': 'ناقص 7',
  'Half-diminished 7': 'نصف ناقص 7',
  'Display': 'العرض',
  'Display configuration': 'إعدادات العرض',
  'Song cards and playlist items': 'كروت الترانيم وعناصر قوائم التشغيل',
  'Keep screen awake': 'إبقاء الشاشة مضاءة',
  'Data': 'البيانات',
  'Backup & export': 'النسخ الاحتياطي والتصدير',
  'Backups, restore, and PDF export': 'النسخ الاحتياطي والاستعادة وتصدير PDF',
  'Lyrics library': 'مكتبة الكلمات',
  'Search, import, and edit lyrics': 'بحث واستيراد وتعديل الكلمات',
  'Lyrics actions': 'إجراءات الكلمات',
  'Sort lyrics': 'ترتيب الكلمات',
  'Newest first': 'الأحدث أولا',
  'Oldest first': 'الأقدم أولا',
  'Most slides': 'الأكثر شرائح',
  'Source': 'المصدر',
  'Delete selected lyrics': 'حذف الكلمات المحددة',
  'Delete {count} selected lyrics entries?':
      'هل تريد حذف {count} عنصر كلمات محدد؟',
  'Lyrics entries deleted': 'تم حذف عناصر الكلمات',
  'Select lyrics': 'تحديد الكلمات',
  'Unselect lyrics': 'إلغاء تحديد الكلمات',
  'Lyrics rights: tasbe7na.com': 'حقوق الكلمات: tasbe7na.com',
  'Lyrics rights are preserved for tasbe7na.com':
      'حقوق الكلمات محفوظة لموقع tasbe7na.com',
  '{loaded} of {total} lyrics entries': '{loaded} من {total} عنصر كلمات',
  '{loaded} of {total} search results': '{loaded} من {total} نتيجة بحث',
  'Repeat marker': 'علامة التكرار',
  'Non-ready songs': 'الترانيم غير الجاهزة',
  'Incomplete song color': 'لون الترنيمة غير الجاهزة',
  'Color': 'اللون',
  'No color': 'بدون لون',
  'Soft color': 'لون هادئ',
  'Strong color': 'لون واضح',
  'Amber': 'عنبر',
  'Red': 'أحمر',
  'Blue': 'أزرق',
  'Green': 'أخضر',
  'Purple': 'بنفسجي',
  'Lyrics display': 'عرض الكلمات',
  'Lyrics font size': 'حجم خط الكلمات',
  'Playlist items': 'عناصر قوائم التشغيل',
  'Backup': 'النسخ الاحتياطي',
  'Database backup': 'نسخ قاعدة البيانات',
  'Songs, playlists, tags, and settings':
      'الترانيم وقوائم التشغيل والوسوم والإعدادات',
  'Full backup': 'نسخ احتياطي كامل',
  'Database and copied media files': 'قاعدة البيانات وملفات الوسائط المنسوخة',
  'Restore database': 'استعادة قاعدة البيانات',
  'Restores database only': 'استعادة قاعدة البيانات فقط',
  'Full restore': 'استعادة كاملة',
  'Restores database and media files': 'استعادة قاعدة البيانات وملفات الوسائط',
  'Export songs PDF': 'تصدير الترانيم PDF',
  'About': 'حول التطبيق',
  'Offline music library.': 'مكتبة موسيقية بدون إنترنت.',
  'Personal song and piano tutorial library.':
      'مكتبة شخصية للترانيم ودروس البيانو.',
  'Version': 'الإصدار',
  'Developer': 'المطور',
  'Developed by': 'تم التطوير بواسطة',
  'Email': 'البريد الإلكتروني',
  'Unable to open email': 'تعذر فتح البريد الإلكتروني',
  'Restore will replace the current local library.':
      'ستستبدل الاستعادة المكتبة المحلية الحالية.',
  'Full restore will replace the current database and copied media files.':
      'ستستبدل الاستعادة الكاملة قاعدة البيانات الحالية وملفات الوسائط المنسوخة.',
  'Restore': 'استعادة',
  'Backup cancelled': 'تم إلغاء النسخ الاحتياطي',
  'Database exported': 'تم تصدير قاعدة البيانات',
  'Backup failed': 'فشل النسخ الاحتياطي',
  'Full backup exported': 'تم تصدير النسخة الكاملة',
  'Restore cancelled': 'تم إلغاء الاستعادة',
  'Database restored': 'تمت استعادة قاعدة البيانات',
  'Restore failed': 'فشلت الاستعادة',
  'Full backup restored': 'تمت استعادة النسخة الكاملة',
  'No songs to export': 'لا توجد ترانيم للتصدير',
  'Export cancelled': 'تم إلغاء التصدير',
  'Songs exported': 'تم تصدير الترانيم',
  'Save locally': 'حفظ محليا',
  'Save to Google Drive': 'حفظ إلى Google Drive',
  'Choose Drive in the save picker': 'اختر Drive من نافذة الحفظ',
  'From local file': 'من ملف محلي',
  'From Google Drive': 'من Google Drive',
  'Choose Drive in the file picker': 'اختر Drive من نافذة اختيار الملفات',
  'Export songs': 'تصدير الترانيم',
  'Export': 'تصدير',
  'Include': 'تضمين',
  'Title': 'العنوان',
  'Lyrics': 'الكلمات',
  'Find in lyrics library': 'بحث في مكتبة الكلمات',
  'Lyrics imported': 'تم استيراد الكلمات',
  'Import lyrics': 'استيراد كلمات',
  'Search lyrics library': 'بحث في مكتبة الكلمات',
  'No lyrics': 'لا توجد كلمات',
  'No lyrics found': 'لا توجد كلمات مطابقة',
  'No lyrics entries': 'لا توجد عناصر كلمات',
  'Add lyrics entry': 'إضافة عنصر كلمات',
  'Edit lyrics entry': 'تعديل عنصر الكلمات',
  'Delete lyrics entry': 'حذف عنصر الكلمات',
  'Lyrics entry saved': 'تم حفظ عنصر الكلمات',
  'Lyrics entry deleted': 'تم حذف عنصر الكلمات',
  'Import': 'استيراد',
  'Import JSON': 'استيراد JSON',
  'Import lyrics JSON': 'استيراد كلمات JSON',
  'Importing lyrics JSON': 'جار استيراد كلمات JSON',
  'Lyrics JSON imported': 'تم استيراد كلمات JSON ({count})',
  'This will merge the selected lyrics into the library. Custom entries will stay saved.':
      'سيتم دمج الكلمات المختارة داخل المكتبة. العناصر المخصصة ستبقى محفوظة.',
  'Replace from JSON': 'استبدال من JSON',
  'Replace lyrics library': 'استبدال مكتبة الكلمات',
  'This will replace the searchable lyrics library. Existing songs will keep their copied lyrics.':
      'سيتم استبدال مكتبة الكلمات القابلة للبحث. الترانيم الحالية ستحتفظ بالكلمات المنسوخة داخلها.',
  'Replace': 'استبدال',
  'Lyrics library updated': 'تم تحديث مكتبة الكلمات ({count})',
  'Import failed': 'فشل الاستيراد',
  'Export failed': 'فشل التصدير',
  'Export lyrics library JSON': 'تصدير مكتبة الكلمات JSON',
  'Export lyrics library': 'تصدير مكتبة الكلمات',
  'Export lyrics library to Drive': 'تصدير مكتبة الكلمات إلى Drive',
  'Exporting lyrics library': 'جار تصدير مكتبة الكلمات',
  'Lyrics library exported': 'تم تصدير مكتبة الكلمات',
  'Use these lyrics': 'استخدم هذه الكلمات',
  'Slides': 'الشرائح',
  'Chorus': 'الكورَس',
  'Verse slides': 'شرائح الآيات',
  'Show chorus first': 'عرض الكورَس أولا',
  'The chorus is also shown after every verse slide.':
      'يظهر الكورَس أيضا بعد كل شريحة آية.',
  'Optional. Separate chorus slides with ---':
      'اختياري. افصل بين شرائح الكورَس باستخدام ---',
  'Separate slides with ---': 'افصل بين الشرائح باستخدام ---',
  'Separate verse slides with ---': 'افصل بين شرائح الآيات باستخدام ---',
  'Add at least one slide': 'أضف شريحة واحدة على الأقل',
  'Add at least one verse or chorus slide':
      'أضف شريحة آية أو كورَس واحدة على الأقل',
  '{count} slides': '{count} شرائح',
  'Previous slide': 'الشريحة السابقة',
  'Next slide': 'الشريحة التالية',
  'Title is required': 'العنوان مطلوب',
  'Musical notes': 'النوتة الموسيقية',
  'Rhythm': 'الإيقاع',
  'Scale': 'المقام',
  'Scale type': 'نوع المقام',
  'Tempo': 'السرعة',
  'Chords': 'الأوتار',
  'Quarter Tone': 'ربع تون',
  'Tags': 'الوسوم',
  'Media': 'الوسائط',
  'Song saved': 'تم حفظ الترنيمة',
  'Save failed': 'فشل الحفظ',
  'Delete failed': 'فشل الحذف',
  'Add failed': 'فشلت الإضافة',
  'Update failed': 'فشل التحديث',
  'Ready': 'جاهزة',
  'Has enough information for use': 'بها المعلومات الكافية للاستخدام',
  'Mark ready': 'تحديد كجاهزة',
  'Mark not ready': 'تحديد كغير جاهزة',
  'Search hymns': 'ابحث في الترانيم',
  'Clear search': 'مسح البحث',
  'Library unavailable': 'المكتبة غير متاحة',
  'No favorite songs': 'لا توجد ترانيم مفضلة',
  'No songs found': 'لا توجد ترانيم',
  'Select all visible': 'تحديد كل الظاهر',
  'Delete selected': 'حذف المحدد',
  'Clear selection': 'مسح التحديد',
  '{count} selected': 'تم تحديد {count}',
  'Delete selected songs': 'حذف الترانيم المحددة',
  'Delete {count} selected song(s) from the library?':
      'هل تريد حذف {count} ترنيمة محددة من المكتبة؟',
  'Songs deleted': 'تم حذف الترانيم',
  'Songs added to playlists': 'تمت إضافة الترانيم إلى قوائم التشغيل',
  'Add to playlists': 'إضافة إلى قوائم التشغيل',
  'Add "{name}"': 'إضافة "{name}"',
  'No playlists yet': 'لا توجد قوائم تشغيل بعد',
  'Playlists updated': 'تم تحديث قوائم التشغيل',
  'Song not found': 'الترنيمة غير موجودة',
  'Remove favorite': 'إزالة من المفضلة',
  'Add favorite': 'إضافة إلى المفضلة',
  'Delete song': 'حذف الترنيمة',
  'Delete "{name}" from the library?': 'هل تريد حذف "{name}" من المكتبة؟',
  'Song deleted': 'تم حذف الترنيمة',
  'New playlist': 'قائمة تشغيل جديدة',
  'Favorite': 'مفضلة',
  'My Key': 'مفتاحي',
  'Transpose': 'النقل',
  'Original Scale': 'المقام الأصلي',
  'My Scale': 'مقامي',
  'Original Key': 'المفتاح الأصلي',
  'BPM': 'BPM',
  'Rhythm Details': 'تفاصيل الإيقاع',
  'Primary: {value}': 'أساسي: {value}',
  'Item {index}: {value}': 'عنصر {index}: {value}',
  'Chord Images': 'صور الأوتار',
  'Melody Images': 'صور اللحن',
  'Performance Video': 'فيديو الأداء',
  'Audio': 'الصوت',
  'Vocals Only': 'الصوت فقط',
  'Trim media': 'قص الوسائط',
  'Reset': 'إعادة ضبط',
  'Media file is missing.': 'ملف الوسائط غير موجود.',
  'Media duration is unavailable.': 'مدة الوسائط غير متاحة.',
  'Start': 'البداية',
  'End': 'النهاية',
  'Selected': 'المحدد',
  'Total': 'الإجمالي',
  'Drag handles': 'اسحب المؤشرات',
  'Preview selection': 'معاينة الجزء المحدد',
  'Play selected part': 'تشغيل الجزء المحدد',
  'Pause preview': 'إيقاف المعاينة',
  'Go to start': 'اذهب للبداية',
  'Go to end': 'اذهب للنهاية',
  'Preview unavailable': 'المعاينة غير متاحة',
  'Hours': 'ساعات',
  'Minutes': 'دقائق',
  'Seconds': 'ثواني',
  'Fast trim': 'قص سريع',
  'The selected copied media file will be replaced after the trim succeeds.':
      'سيتم استبدال ملف الوسائط المنسوخ بعد نجاح القص.',
  'Trimming...': 'جاري القص...',
  'Save trim': 'حفظ القص',
  'Trim failed': 'فشل القص',
  'Media trimmed': 'تم قص الوسائط',
  'No {title}': 'لا يوجد {title}',
  'Song Name': 'اسم الترنيمة',
  'Song name': 'اسم الترنيمة',
  'My Starting Key': 'مفتاح البداية الخاص بي',
  'Transpose Value': 'قيمة النقل',
  'Decrease transpose': 'تقليل النقل',
  'Increase transpose': 'زيادة النقل',
  'No tags selected': 'لا توجد وسوم محددة',
  'Select tags': 'اختيار الوسوم',
  'Optional Information': 'معلومات اختيارية',
  'Original Starting Key': 'مفتاح البداية الأصلي',
  'Quarter-toned keys': 'مفاتيح ربع التون',
  'Quarter-toned Keys': 'مفاتيح ربع التون',
  'No quarter-toned keys': 'لا توجد مفاتيح ربع تون',
  'Rhythm Items': 'عناصر الإيقاع',
  'Add item': 'إضافة عنصر',
  'No rhythm items selected': 'لا توجد عناصر إيقاع محددة',
  'Primary': 'أساسي',
  'Make primary': 'اجعله أساسيا',
  'Rhythm item': 'عنصر إيقاع',
  'No rhythms created yet': 'لم يتم إنشاء إيقاعات بعد',
  'New rhythm': 'إيقاع جديد',
  'Rhythm Name': 'اسم الإيقاع',
  'Section': 'القسم',
  'Annual, Kiahk, Holy Week': 'سنوي، كيهك، أسبوع الآلام',
  'Add media': 'إضافة وسائط',
  'Type': 'النوع',
  'External link': 'رابط خارجي',
  'URL': 'الرابط',
  'Label': 'التسمية',
  'Choose file': 'اختيار ملف',
  'No media added': 'لم تتم إضافة وسائط',
  'Chord image': 'صورة وتر',
  'Melody image': 'صورة لحن',
  'Song audio': 'صوت الترنيمة',
  'Vocal audio': 'الصوت فقط',
  'Performance video': 'فيديو الأداء',
  'No items': 'لا توجد عناصر',
  'Unable to open link': 'تعذر فتح الرابط',
  'Image file was not found': 'ملف الصورة غير موجود',
  'Audio file was not found': 'ملف الصوت غير موجود',
  'Video file is missing.': 'ملف الفيديو مفقود.',
  'Video file was not found.': 'ملف الفيديو غير موجود.',
  'Unable to open video': 'تعذر فتح الفيديو',
  'Audio file is missing.': 'ملف الصوت مفقود.',
  'Audio file was not found.': 'ملف الصوت غير موجود.',
  'Unable to open audio': 'تعذر فتح الصوت',
  'Chord Tutorials': 'دروس الأوتار',
  'Add tutorial': 'إضافة درس',
  'No tutorials added': 'لم تتم إضافة دروس',
  'No tutorials': 'لا توجد دروس',
  'Note items': 'عناصر الملاحظات',
  'Add note item': 'إضافة عنصر ملاحظة',
  'No note items': 'لا توجد عناصر ملاحظات',
  'New note item': 'عنصر ملاحظة جديد',
  'Edit note item': 'تعديل عنصر الملاحظة',
  'Practice tip': 'نصيحة تدريب',
  'Chord structure': 'تركيب الوتر',
  'What it shows': 'ماذا تعرض',
  'How to read it': 'طريقة قراءتها',
  'Example: C to G': 'مثال: من C إلى G',
  'Practice step': 'خطوة تدريب',
  'Filters': 'التصفية',
  'Min BPM': 'أقل BPM',
  'Max BPM': 'أعلى BPM',
  'No tags available': 'لا توجد وسوم متاحة',
  'My key': 'مفتاحي',
  'Original key': 'المفتاح الأصلي',
  'Quarter tone': 'ربع تون',
  'Video': 'الفيديو',
  'Links': 'الروابط',
  'Add link': 'إضافة رابط',
  'No links': 'لا توجد روابط',
  'New link': 'رابط جديد',
  'Edit link': 'تعديل الرابط',
  'Custom fields': 'حقول مخصصة',
  'Add field': 'إضافة حقل',
  'No custom fields': 'لا توجد حقول مخصصة',
  'New field': 'حقل جديد',
  'Edit field': 'تعديل الحقل',
  'Value': 'القيمة',
  'Chord images': 'صور الأوتار',
  'Ascending': 'تصاعدي',
  'Descending': 'تنازلي',
  'Alphabetical': 'أبجدي',
  'Newest': 'الأحدث',
  'Oldest': 'الأقدم',
  'Recently updated': 'تم تحديثها مؤخرا',
  'Favorite first': 'المفضلة أولا',
  'Last Updated': 'آخر تحديث',
  'Key': 'المفتاح',
  'Tag': 'وسم',
  'Back 5 seconds': 'رجوع 5 ثوان',
  'Stop audio': 'إيقاف الصوت',
  'Minimize player': 'تصغير المشغل',
  'Open': 'فتح',
  'Pause': 'إيقاف مؤقت',
  'Play': 'تشغيل',
  'Forward 5 seconds': 'تقديم 5 ثوان',
  'Playback speed': 'سرعة التشغيل',
  'Add playlist': 'إضافة قائمة تشغيل',
  'No playlists': 'لا توجد قوائم تشغيل',
  'Create playlist': 'إنشاء قائمة تشغيل',
  'Rename playlist': 'إعادة تسمية قائمة التشغيل',
  'Playlist Name': 'اسم قائمة التشغيل',
  'Playlist saved': 'تم حفظ قائمة التشغيل',
  '{count} songs': '{count} ترانيم',
  'Add songs': 'إضافة ترانيم',
  'No songs added': 'لم تتم إضافة ترانيم',
  'Delete playlist': 'حذف قائمة التشغيل',
  'Delete "{name}"?': 'هل تريد حذف "{name}"؟',
  'All songs are already in this playlist':
      'كل الترانيم موجودة بالفعل في هذه القائمة',
  'Search songs': 'بحث في الترانيم',
  'No matching songs': 'لا توجد ترانيم مطابقة',
  'Playlist deleted': 'تم حذف قائمة التشغيل',
  'Songs added': 'تمت إضافة الترانيم',
  'Song removed': 'تمت إزالة الترنيمة',
  'Remove failed': 'فشلت الإزالة',
  'Search notes': 'بحث في الملاحظات',
  'Sort notes': 'ترتيب الملاحظات',
  'Modified newest': 'الأحدث تعديلا',
  'Modified oldest': 'الأقدم تعديلا',
  'Title A-Z': 'العنوان أ-ي',
  'Title Z-A': 'العنوان ي-أ',
  'Add note': 'إضافة ملاحظة',
  'Sort by date': 'ترتيب حسب التاريخ',
  'Sort by title': 'ترتيب حسب العنوان',
  'No notes': 'لا توجد ملاحظات',
  'No notes found': 'لا توجد ملاحظات',
  'Create note': 'إنشاء ملاحظة',
  'Delete note': 'حذف الملاحظة',
  'Note deleted': 'تم حذف الملاحظة',
  'Modified {date}': 'تم التعديل {date}',
  'Pinned': 'مثبتة',
  'Unpin': 'إلغاء التثبيت',
  'Pin': 'تثبيت',
  'New Note': 'ملاحظة جديدة',
  'Edit Note': 'تعديل ملاحظة',
  'Note': 'ملاحظة',
  'Images': 'الصور',
  'Add image': 'إضافة صورة',
  'No images': 'لا توجد صور',
  'Remove image': 'إزالة الصورة',
  'Add a title or note text': 'أضف عنوانا أو نصا للملاحظة',
  'Untitled note': 'ملاحظة بدون عنوان',
  'No chord tutorials': 'لا توجد دروس أوتار',
  'Selected chords': 'الأوتار المختارة',
  'No chords selected': 'لا توجد أوتار مختارة',
  'Select chords': 'اختيار الأوتار',
  'Search chords': 'بحث في الأوتار',
  'No matching items': 'لا توجد عناصر مطابقة',
  'Create tutorial': 'إنشاء درس',
  'Tutorial saved': 'تم حفظ الدرس',
  'Tutorial deleted': 'تم حذف الدرس',
  'Delete tutorial': 'حذف الدرس',
  'Add chord tutorial': 'إضافة درس وتر',
  'No chords for this type': 'لا توجد أوتار لهذا النوع',
  'Chord not found': 'الوتر غير موجود',
  'New chord': 'وتر جديد',
  'New chord tutorial': 'درس وتر جديد',
  'Edit chord': 'تعديل الوتر',
  'Chord Name': 'اسم الوتر',
  'Choose image': 'اختيار صورة',
  'Clear image': 'مسح الصورة',
  'Choose video': 'اختيار فيديو',
  'Clear video': 'مسح الفيديو',
  'Chord saved': 'تم حفظ الوتر',
  'Chord deleted': 'تم حذف الوتر',
  'Delete chord tutorial': 'حذف درس الوتر',
  'No circle tutorials': 'لا توجد دروس لدائرة الخامسات',
  'Circle tutorial not found': 'درس دائرة الخامسات غير موجود',
  'New circle tutorial': 'درس دائرة خامسات جديد',
  'Edit circle tutorial': 'تعديل درس دائرة الخامسات',
  'Summary': 'الملخص',
  'Rhythms': 'الإيقاعات',
  'No tags': 'لا توجد وسوم',
  'Create tag': 'إنشاء وسم',
  'Add tag': 'إضافة وسم',
  'New tag': 'وسم جديد',
  'Edit tag': 'تعديل الوسم',
  'Tag Name': 'اسم الوسم',
  'Tag saved': 'تم حفظ الوسم',
  'Tag deleted': 'تم حذف الوسم',
  'Delete tag': 'حذف الوسم',
  'Delete "{name}"? Songs using it will keep no tag.':
      'هل تريد حذف "{name}"؟ ستفقد الترانيم المرتبطة به هذا الوسم.',
  'No rhythms': 'لا توجد إيقاعات',
  'Create rhythm': 'إنشاء إيقاع',
  'Add rhythm': 'إضافة إيقاع',
  'Edit rhythm': 'تعديل الإيقاع',
  'Rhythm saved': 'تم حفظ الإيقاع',
  'Rhythm deleted': 'تم حذف الإيقاع',
  'Delete rhythm': 'حذف الإيقاع',
  'Delete "{name}"? Songs using it will keep the rhythm text.':
      'هل تريد حذف "{name}"؟ ستحتفظ الترانيم المرتبطة به بنص الإيقاع.',
  'Add scale': 'إضافة مقام',
  'No scales': 'لا توجد مقامات',
  'Create scale': 'إنشاء مقام',
  'No scales for this type': 'لا توجد مقامات لهذا النوع',
  'Scale not found': 'المقام غير موجود',
  'New scale': 'مقام جديد',
  'Edit scale': 'تعديل المقام',
  'Scale Chords': 'أوتار المقام',
  'Select scale chords': 'اختيار أوتار المقام',
  'Chords: {value}': 'الأوتار: {value}',
  'Name': 'الاسم',
  'Major, Minor, Bayati': 'كبير، صغير، بياتي',
  'Keys/Notes': 'المفاتيح/النوتات',
  'Formula': 'الصيغة',
  '1, 1, 1/2, 1, 1, 1, 1/2': '1, 1, 1/2, 1, 1, 1, 1/2',
  'C, D, E, F, G, A, B': 'C, D, E, F, G, A, B',
  'C, E, G': 'C, E, G',
  'E, G, C': 'E, G, C',
  'Inversions': 'الانقلابات',
  'Relative Chord': 'الوتر النسبي',
  'Relative chord': 'وتر نسبي',
  'Relative minor': 'الصغير النسبي',
  'Relative major': 'الكبير النسبي',
  'Choose relative chord': 'اختيار الوتر النسبي',
  'No relative chord': 'لا يوجد وتر نسبي',
  'No relative chord selected': 'لم يتم اختيار وتر نسبي',
  'Add inversion': 'إضافة انقلاب',
  'No inversions': 'لا توجد انقلابات',
  'New inversion': 'انقلاب جديد',
  'Edit inversion': 'تعديل الانقلاب',
  'Root position': 'الوضع الأساسي',
  'First inversion': 'الانقلاب الأول',
  'Second inversion': 'الانقلاب الثاني',
  'Third inversion': 'الانقلاب الثالث',
  'Root': 'الأصل',
  'Inversion {index}': 'الانقلاب {index}',
  'Chord Items': 'عناصر الأوتار',
  'Chord Item': 'عنصر أوتار',
  'Chord Item {index}': 'عنصر أوتار {index}',
  'Add chord item': 'إضافة عنصر أوتار',
  'No chord items selected': 'لا توجد عناصر أوتار مختارة',
  'Reorder': 'إعادة ترتيب',
  'Selected order': 'ترتيب المختار',
  'Song main card': 'كارت الترنيمة الرئيسي',
  'No fields selected': 'لا توجد حقول مختارة',
  'How to use it': 'طريقة الاستخدام',
  'Scale saved': 'تم حفظ المقام',
  'Scale deleted': 'تم حذف المقام',
  'Delete scale': 'حذف المقام',
  'Delete "{name}"? Songs that already show this scale will keep the text value.':
      'هل تريد حذف "{name}"؟ ستحتفظ الترانيم التي تعرض هذا المقام بالقيمة النصية.',
};
